### PR TITLE
Make speech page looks consistent with the other webapp

### PR DESCRIPTION
**Pull request by khanghugo**

### CODE REVIEW

**Comment by davehorton** [comment]
maybe fix this warning
```
src/pages/account/speech-services/add-edit.js
  Line 39:7:  'VendorText' is assigned a value but never used  no-unused-vars
```

**Comment by davehorton** [comment]
also these
```
 Line 2:4:     Trailing spaces not allowed  no-trailing-spaces
  Line 3:46:    Trailing spaces not allowed  no-trailing-spaces
  Line 4:27:    Trailing spaces not allowed  no-trailing-spaces
  Line 6:4:     Trailing spaces not allowed  no-trailing-spaces
  Line 7:42:    Trailing spaces not allowed  no-trailing-spaces
  Line 8:25:    Trailing spaces not allowed  no-trailing-spaces
  Line 10:4:    Trailing spaces not allowed  no-trailing-spaces
  Line 11:46:   Trailing spaces not allowed  no-trailing-spaces
  Line 12:27:   Trailing spaces not allowed  no-trailing-spaces
  Line 14:4:    Trailing spaces not allowed  no-trailing-spaces
  Line 15:34:   Trailing spaces not allowed  no-trailing-spaces
  Line 16:22:   Trailing spaces not allowed  no-trailing-spaces
  Line 18:4:    Trailing spaces not allowed  no-trailing-spaces
  Line 19:42:   Trailing spaces not allowed  no-trailing-spaces
 ```

**Review by davehorton — CHANGES_REQUESTED** [review]
Can you look into these errors I see in the console?  They seem to be related to your changes
```
index.js:1 Warning: Unexpected ref object provided for select. Use either a ref-setter function or React.createRef().
    at select
    at O (http://localhost:3001/static/js/0.chunk.js:195388:6)
    at form
    at O (http://localhost:3001/static/js/0.chunk.js:195388:6)
    at section
    at O (http://localhost:3001/static/js/0.chunk.js:195388:6)
    at Section (http://localhost:3001/static/js/main.chunk.js:3908:21)
    at div
    at O (http://localhost:3001/static/js/0.chunk.js:195388:6)
    at main
    at O (http://localhost:3001/static/js/0.chunk.js:195388:6)
    at InternalMain (http://localhost:3001/static/js/main.chunk.js:11426:82)
    at SpeechServicesAddEdit (http://localhost:3001/static/js/main.chunk.js:34594:84)
    at Route (http://localhost:3001/static/js/0.chunk.js:186946:29)
    at Switch (http://localhost:3001/static/js/0.chunk.js:187148:29)
    at div
    at InternalTemplate (http://localhost:3001/static/js/main.chunk.js:9917:86)
    at Route (http://localhost:3001/static/js/0.chunk.js:186946:29)
    at Switch (http://localhost:3001/static/js/0.chunk.js:187148:29)
    at Router (http://localhost:3001/static/js/0.chunk.js:186581:30)
    at BrowserRouter (http://localhost:3001/static/js/0.chunk.js:186201:35)
    at Routes (http://localhost:3001/static/js/main.chunk.js:928:81)
    at ResponsiveProvider (http://localhost:3001/static/js/main.chunk.js:12082:93)
    at ModalProvider (http://localhost:3001/static/js/main.chunk.js:11766:91)
    at NotificationProvider (http://localhost:3001/static/js/main.chunk.js:11931:85)
    at CurrentMenuProvider (http://localhost:3001/static/js/main.chunk.js:11612:95)
    at Ge (http://localhost:3001/static/js/0.chunk.js:195299:67)
```

**Comment by khanghugo** [comment]
The fix is super simple. The way reference for form is made seems to be not up to date for newer React.

**Comment by khanghugo** [comment]
I suggest this should be also changed for jambonz-webapp too because it is also throwing this same error.

**Review by davehorton — APPROVED** [review]

**Comment by davehorton** [comment]
yes please give me a PR with same change there

**Pull request merged**
